# Generated by Django 5.2.11 on 2026-02-24 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employees', models.ManyToManyField(blank=True, to='employee.employee')),
            ],
        ),
    ]
